services:
  proxyserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETOS: ${TARGETOS}
        TARGETARCH: ${TARGETARCH}
        CA_CERT_PATH: ${CA_CERT_PATH}
        CONFIG_FILE: ${CONFIG_FILE}
    ports:
      - "6445:6445"
      - "6446:6446"
    environment:
      CONFIG_FILE: "/config/config.yaml"
      LOG_LEVEL: "info"
      LOG_FILE_PATH: "/logs/proxy.log"
    volumes:
      - ./config:/config
      - ./logs:/logs
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
