routes:
  - name: "grafana"
    listenport: 6442
    protocol: "https"
    pattern: "/"
    target:
        name: "grafana-p920s"
        protocol: "https"
        host: "192.168.2.130"
        port: 6443
        certfile: "/home/rupesh/aqrtr/security/ssl/clients/k8s/k8s.crt"
        keyfile: "/home/rupesh/aqrtr/security/ssl/clients/k8s/k8s.key"