routes:
  - name: "proxy"
    listenHost: "0.0.0.0"
    listenport: 6446
    protocol: "http"
    pattern: "/"
    target:
        - name: "grafana"
          pathprefix: "/grafana"
          protocol: "http"
          host: "10.0.0.213"
          port: 3000
        - name: "ollama"
          pathprefix: "/ollama"
          protocol: "http"
          host: "10.0.0.213"
          port: 11434
