routes:
  - name: "grafana"
    listenport: 3000
    protocol: "http"
    proxyprotocol: "http"
    target:
        name: "grafana-local"
        protocol: "http"
        host: "127.0.0.1"
        port: 3010