routes:
  - name: "grafana"
    listenHost: "0.0.0.0"
    listenport: 6446
    protocol: "http"
    pattern: "/"
    target:
        name: "grafana-p920s"
        protocol: "http"
        host: "10.0.0.213"
        port: 3000
