routes:
  - name: "grafana"
    listenHost: "0.0.0.0"
    listenport: 6442
    protocol: "http"
    certFile: "/home/rupesh/aqrtr/security/ssl/clients/k8s/k8s.crt"
    keyFile: "/home/rupesh/aqrtr/security/ssl/clients/k8s/k8s.key"
    pattern: "/"
    target:
        name: "grafana-p920s"
        protocol: "http"
        host: "10.0.1.213"
        port: 3000
        certfile: "/home/rupesh/aqrtr/security/ssl/clients/k8s/k8s.crt"
        keyfile: "/home/rupesh/aqrtr/security/ssl/clients/k8s/k8s.key"