routes:
  - name: "grafana"
    listenport: 3009
    protocol: "http"
    pattern: "/"
    target:
        name: "grafana-p920s"
        protocol: "http"
        host: "10.0.0.213"
        port: 3000
        certfile: ""
        keyfile: ""