routes:
  - name: "grafana"
    listenHost: "10.0.0.213"
    listenport: 6445
    protocol: "https"
    certFile: "config/keystore/server/k8s.crt"
    keyFile: "config/keystore/server/k8s.key"
    pattern: "/"
    target:
        name: "grafana-p920s"
        protocol: "https"
        host: "10.0.0.213"
        port: 6443
        certfile: "config/keystore/targets/k8s/k8s.crt"
        keyfile: "config/keystore/targets/k8s/k8s.key"
        cacert: "config/keystore/targets/k8s/ca.crt"